// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package snowflake

import (
	"github.com/google/wire"
	"github.com/imkuqin-zw/uuid-generator/internal/snowflake"
	"github.com/imkuqin-zw/uuid-generator/pkg/genproto/api"
	"github.com/imkuqin-zw/uuid-generator/pkg/genproto/api/grpc"
	"github.com/imkuqin-zw/yggdrasil/pkg/server/grpc"
)

// Injectors from wire.go:

func newApiServer() api.SnowflakeServer {
	coordinator := snowflake.NewEtcdv3Coordinator()
	snowflakeSnowflake := snowflake.NewWorker(coordinator)
	snowflakeServer := snowflake.NewService(snowflakeSnowflake)
	return snowflakeServer
}

// wire.go:

var providerSet = wire.NewSet(snowflake.NewEtcdv3Coordinator, snowflake.NewWorker, snowflake.NewService)

func RegisterService() {
	svr := newApiServer()
	grpc.RegisterService(&grpcimpl.SnowflakeServiceDesc, svr)
}
