// Copyright 2022 The imkuqin-zw Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.3
// source: api/segment.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchSegmentNextReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *FetchSegmentNextReq) Reset() {
	*x = FetchSegmentNextReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_segment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchSegmentNextReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSegmentNextReq) ProtoMessage() {}

func (x *FetchSegmentNextReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_segment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSegmentNextReq.ProtoReflect.Descriptor instead.
func (*FetchSegmentNextReq) Descriptor() ([]byte, []int) {
	return file_api_segment_proto_rawDescGZIP(), []int{0}
}

func (x *FetchSegmentNextReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

var File_api_segment_proto protoreflect.FileDescriptor

var file_api_segment_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x28, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x69, 0x6d, 0x6b, 0x75, 0x71, 0x69, 0x6e, 0x5f, 0x7a, 0x77, 0x2e, 0x75, 0x75, 0x69, 0x64, 0x5f,
	0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x10, 0x61,
	0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x27, 0x0a, 0x13, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x4e,
	0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x32, 0x85, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x7a, 0x0a, 0x09, 0x46, 0x65, 0x74, 0x63, 0x68, 0x4e, 0x65, 0x78,
	0x74, 0x12, 0x3d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x69,
	0x6d, 0x6b, 0x75, 0x71, 0x69, 0x6e, 0x5f, 0x7a, 0x77, 0x2e, 0x75, 0x75, 0x69, 0x64, 0x5f, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x2e, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x69, 0x6d,
	0x6b, 0x75, 0x71, 0x69, 0x6e, 0x5f, 0x7a, 0x77, 0x2e, 0x75, 0x75, 0x69, 0x64, 0x5f, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x55, 0x49, 0x44,
	0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x6d, 0x6b, 0x75, 0x71, 0x69, 0x6e, 0x2d, 0x7a, 0x77, 0x2f, 0x75, 0x75, 0x69, 0x64, 0x2d, 0x67,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x65, 0x6e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_segment_proto_rawDescOnce sync.Once
	file_api_segment_proto_rawDescData = file_api_segment_proto_rawDesc
)

func file_api_segment_proto_rawDescGZIP() []byte {
	file_api_segment_proto_rawDescOnce.Do(func() {
		file_api_segment_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_segment_proto_rawDescData)
	})
	return file_api_segment_proto_rawDescData
}

var file_api_segment_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_segment_proto_goTypes = []interface{}{
	(*FetchSegmentNextReq)(nil), // 0: com.github.imkuqin_zw.uuid_generator.api.FetchSegmentNextReq
	(*UUID)(nil),                // 1: com.github.imkuqin_zw.uuid_generator.api.UUID
}
var file_api_segment_proto_depIdxs = []int32{
	0, // 0: com.github.imkuqin_zw.uuid_generator.api.Segment.FetchNext:input_type -> com.github.imkuqin_zw.uuid_generator.api.FetchSegmentNextReq
	1, // 1: com.github.imkuqin_zw.uuid_generator.api.Segment.FetchNext:output_type -> com.github.imkuqin_zw.uuid_generator.api.UUID
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_segment_proto_init() }
func file_api_segment_proto_init() {
	if File_api_segment_proto != nil {
		return
	}
	file_api_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_segment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchSegmentNextReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_segment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_segment_proto_goTypes,
		DependencyIndexes: file_api_segment_proto_depIdxs,
		MessageInfos:      file_api_segment_proto_msgTypes,
	}.Build()
	File_api_segment_proto = out.File
	file_api_segment_proto_rawDesc = nil
	file_api_segment_proto_goTypes = nil
	file_api_segment_proto_depIdxs = nil
}
