// Copyright 2022 The imkuqin-zw Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-yggdrasil-error. DO NOT EDIT.

package api

import (
	code "google.golang.org/genproto/googleapis/rpc/code"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the yggdrasil package it is being compiled against.

var SeqsvrErrReason_code = map[int32]code.Code{
	0: code.Code(0),
	1: code.Code(9),
	2: code.Code(9),
}

func (r SeqsvrErrReason) Reason() string {
	return SeqsvrErrReason_name[int32(r)]
}

func (r SeqsvrErrReason) Domain() string {
	return "com.github.imkuqin_zw.uuid_generator.api"
}

func (r SeqsvrErrReason) Code() code.Code {
	return SeqsvrErrReason_code[int32(r)]
}
