// Copyright 2022 The imkuqin-zw Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-yggdrasil-rpc. DO NOT EDIT.

package api

import (
	context "context"
	errors "github.com/imkuqin-zw/yggdrasil/pkg/errors"
	code "google.golang.org/genproto/googleapis/rpc/code"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the yggdrasil package it is being compiled against.

type SnowflakeServer interface {
	FetchNext(context.Context, *FetchSnowflakeNextReq) (*UUID, error)
	UnsafeSnowflakeServer
}

type UnsafeSnowflakeServer interface {
	mustEmbedUnimplementedSnowflakeServer()
}

// UnimplementedSnowflakeServer must be embedded to have forward compatible implementations.
type UnimplementedSnowflakeServer struct {
}

func (UnimplementedSnowflakeServer) FetchNext(context.Context, *FetchSnowflakeNextReq) (*UUID, error) {
	return nil, errors.Errorf(code.Code_UNAUTHENTICATED, "method FetchNext not implemented")
}

func (UnimplementedSnowflakeServer) mustEmbedUnimplementedSnowflakeServer() {}
