// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package alloc

import (
	"github.com/google/wire"
	"github.com/imkuqin-zw/uuid-generator/internal/seqsvr"
)

// Injectors from wire.go:

func newRouter() *seqsvr.Router {
	router := seqsvr.NewRouter()
	return router
}

func newStorage() seqsvr.Storage {
	storage := seqsvr.NewEtcdv3Storage()
	return storage
}

// wire.go:

var providerSet = wire.NewSet(seqsvr.NewTicker, seqsvr.NewRouter, seqsvr.NewEtcdv3Storage)
