// Copyright 2022 The imkuqin-zw Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package alloc

import (
	"github.com/google/wire"
	"github.com/imkuqin-zw/uuid-generator/internal/seqsvr"
)

// Injectors from wire.go:

func newRouter() *seqsvr.Router {
	router := seqsvr.NewRouter()
	return router
}

func newStorage() seqsvr.Storage {
	storage := seqsvr.NewEtcdv3Storage()
	return storage
}

// wire.go:

var providerSet = wire.NewSet(seqsvr.NewTicker, seqsvr.NewRouter, seqsvr.NewEtcdv3Storage)
